################################################################################
# WSJTX Publisher Compose
################################################################################
# docker-compose -f docker-compose.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  wsjtx-services:
    image: wsjtx-services
    restart: unless-stopped

    ports:
      - "2237:2237/udp"
      - "80:80"

    build: 
      context: https://github.com/jeffu231/WSJT-XPublisher.git
      dockerfile: MessagePublisher/Dockerfile
    
   
