################################################################################
# WSJTX Services Compose
# This logic requires access to the host network in order to discover
# the source ip of the incoming udp packets 
################################################################################
# docker-compose -f docker-compose.yml -p wsjtx-services up
################################################################################

services:
  wsjtx-services:
    image: wsjtx-services
    restart: unless-stopped

    network_mode: "host"
   
    build: 
      context: https://github.com/jeffu231/WSJT-XPublisher.git
      dockerfile: MessagePublisher/Dockerfile
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN} 
    
