################################################################################
# WSJTX Services Compose
# This logic requires access to the host network in order to discover
# the source ip of the incoming udp packets 
################################################################################
# docker-compose -f docker-compose.yml -p wsjtx-services up
################################################################################

services:
  wsjtx-services:
    image: ghcr.io/jeffu231/wsjt-xpublisher:latest
    container_name: wsjtx-publisher
    restart: unless-stopped

    network_mode: "host"
    
